INSERT INTO departamento (id_depart, nam_depart) VALUES (1, 'AMAZONAS');
INSERT INTO departamento (id_depart, nam_depart) VALUES (2, 'ANTIOQUIA');
INSERT INTO departamento (id_depart, nam_depart) VALUES (3, 'ARAUCA');
INSERT INTO departamento (id_depart, nam_depart) VALUES (4, 'ATLANTICO');
INSERT INTO departamento (id_depart, nam_depart) VALUES (5, 'BOLIVAR');
INSERT INTO departamento (id_depart, nam_depart) VALUES (6, 'BOYACA');
INSERT INTO departamento (id_depart, nam_depart) VALUES (7, 'CALDAS');
INSERT INTO departamento (id_depart, nam_depart) VALUES (8, 'CAQUETÁ');
INSERT INTO departamento (id_depart, nam_depart) VALUES (9, 'CASANARE');
INSERT INTO departamento (id_depart, nam_depart) VALUES (10, 'CAUCA');
INSERT INTO departamento (id_depart, nam_depart) VALUES (11, 'CESAR');
INSERT INTO departamento (id_depart, nam_depart) VALUES (12, 'CHOCO');
INSERT INTO departamento (id_depart, nam_depart) VALUES (13, 'CORDOBA');
INSERT INTO departamento (id_depart, nam_depart) VALUES (14, 'CUNDINAMARCA');
INSERT INTO departamento (id_depart, nam_depart) VALUES (15, 'GUAINIA');
INSERT INTO departamento (id_depart, nam_depart) VALUES (16, 'GUAVIARE');
INSERT INTO departamento (id_depart, nam_depart) VALUES (17, 'HUILA');
INSERT INTO departamento (id_depart, nam_depart) VALUES (18, 'LA GUAJIRA');
INSERT INTO departamento (id_depart, nam_depart) VALUES (19, 'MAGDALENA');
INSERT INTO departamento (id_depart, nam_depart) VALUES (20, 'META');
INSERT INTO departamento (id_depart, nam_depart) VALUES (21, 'NARIÑO');
INSERT INTO departamento (id_depart, nam_depart) VALUES (22, 'NORTE DE SANTANDER');
INSERT INTO departamento (id_depart, nam_depart) VALUES (23, 'PUTUMAYO');
INSERT INTO departamento (id_depart, nam_depart) VALUES (24, 'QUINDIO');
INSERT INTO departamento (id_depart, nam_depart) VALUES (25, 'RISARALDA');
INSERT INTO departamento (id_depart, nam_depart) VALUES (26, 'SAN ANDRÉS Y ROVIDENCIA');
INSERT INTO departamento (id_depart, nam_depart) VALUES (27, 'SANTANDER');
INSERT INTO departamento (id_depart, nam_depart) VALUES (28, 'SUCRE');
INSERT INTO departamento (id_depart, nam_depart) VALUES (29, 'TOLIMA');
INSERT INTO departamento (id_depart, nam_depart) VALUES (30, 'VALLE DEL CAUCA');
INSERT INTO departamento (id_depart, nam_depart) VALUES (31, 'VAUPES');
INSERT INTO departamento (id_depart, nam_depart) VALUES (32, 'VICHADA');