INSERT INTO municipio (id_muni, nam_muni) VALUES (1, "EL ENCANTO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (2, "LA CHORRERA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (3, "LA PEDRERA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (4, "LA VICTORIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (5, "LETICIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (6, "MIRITI"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (7, "PUERTO ALEGRIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (8, "PUERTO ARICA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (9, "PUERTO NARIÑO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (10, "PUERTO SANTANDER"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (11, "TURAPACA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (12, "ABEJORRAL"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (13, "ABRIAQUI"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (14, "ALEJANDRIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (15, "AMAGA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (16, "AMALFI"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (17, "ANDES"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (18, "ANGELOPOLIS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (19, "ANGOSTURA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (20, "ANORI"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (21, "ANTIOQUIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (22, "ANZA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (23, "APARTADO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (24, "ARBOLETES"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (25, "ARGELIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (26, "ARMENIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (27, "BARBOSA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (28, "BELLO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (29, "BELMIRA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (30, "BETANIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (31, "BETULIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (32, "BOLIVAR"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (33, "BRICEÑO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (34, "BURITICA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (35, "CACERES"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (36, "CAICEDO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (37, "CALDAS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (38, "CAMPAMENTO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (39, "CANASGORDAS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (40, "CARACOLI"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (41, "CARAMANTA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (42, "CAREPA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (43, "CARMEN DE VIBORAL"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (44, "CAROLINA DEL PRINCIPE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (45, "CAUCASIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (46, "CHIGORODO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (47, "CISNEROS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (48, "COCORNA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (49, "CONCEPCION"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (50, "CONCORDIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (51, "COPACABANA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (52, "DABEIBA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (53, "DONMATIAS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (54, "EBEJICO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (55, "EL BAGRE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (56, "EL PENOL"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (57, "EL RETIRO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (58, "ENTRERRIOS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (59, "ENVIGADO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (60, "FREDONIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (61, "FRONTINO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (62, "GIRALDO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (63, "GIRARDOTA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (64, "GOMEZ PLATA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (65, "GRANADA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (66, "GUADALUPE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (67, "GUARNE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (68, "GUATAQUE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (69, "HELICONIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (70, "HISPANIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (71, "ITAGUI"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (72, "ITUANGO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (73, "JARDIN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (74, "JERICO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (75, "LA CEJA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (76, "LA ESTRELLA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (77, "LA PINTADA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (78, "LA UNION"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (79, "LIBORINA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (80, "MACEO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (81, "MARINILLA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (82, "MEDELLIN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (83, "MONTEBELLO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (84, "MURINDO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (85, "MUTATA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (86, "NARINO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (87, "NECHI"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (88, "NECOCLI"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (89, "OLAYA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (90, "PEQUE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (91, "PUEBLORRICO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (92, "PUERTO BERRIO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (93, "PUERTO NARE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (94, "PUERTO TRIUNFO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (95, "REMEDIOS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (96, "RIONEGRO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (97, "SABANALARGA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (98, "SABANETA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (99, "SALGAR"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (100, "SAN ANDRES DE CUERQUIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (101, "SAN CARLOS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (102, "SAN FRANCISCO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (103, "SAN JERONIMO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (104, "SAN JOSE DE LA MONTAÑA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (105, "SAN JUAN DE URABA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (106, "SAN LUIS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (107, "SAN PEDRO DE LOS MILAGROS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (108, "SAN PEDRO DE URABA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (109, "SAN RAFAEL"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (110, "SAN ROQUE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (111, "SAN VICENTE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (112, "SANTA BARBARA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (113, "SANTA ROSA DE OSOS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (114, "SANTO DOMINGO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (115, "SANTUARIO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (116, "SEGOVIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (117, "SONSON"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (118, "SOPETRAN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (119, "TAMESIS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (120, "TARAZA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (121, "TARSO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (122, "TITIRIBI"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (123, "TOLEDO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (124, "TURBO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (125, "URAMITA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (126, "URRAO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (127, "VALDIVIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (128, "VALPARAISO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (129, "VEGACHI"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (130, "VENECIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (131, "VIGIA DEL FUERTE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (132, "YALI"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (133, "YARUMAL"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (134, "YOLOMBO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (135, "YONDO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (136, "ZARAGOZA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (137, "ARAUCA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (138, "ARAUQUITA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (139, "CRAVO NORTE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (140, "FORTUL"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (141, "PUERTO RONDON"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (142, "SARAVENA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (143, "TAME"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (144, "BARANOA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (145, "BARRANQUILLA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (146, "CAMPO DE LA CRUZ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (147, "CANDELARIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (148, "GALAPA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (149, "JUAN DE ACOSTA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (150, "LURUACO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (151, "MALAMBO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (152, "MANATI"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (153, "PALMAR DE VARELA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (154, "PIOJO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (155, "POLO NUEVO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (156, "PONEDERA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (157, "PUERTO COLOMBIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (158, "REPELON"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (159, "SABANAGRANDE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (160, "SABANALARGA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (161, "SANTA LUCIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (162, "SANTO TOMAS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (163, "SOLEDAD"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (164, "SUAN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (165, "TUBARA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (166, "USIACURI"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (167, "ACHI"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (168, "ALTOS DEL ROSARIO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (169, "ARENAL"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (170, "ARJONA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (171, "ARROYOHONDO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (172, "BARRANCO DE LOBA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (173, "BRAZUELO DE PAPAYAL"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (174, "CALAMAR"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (175, "CANTAGALLO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (176, "CARTAGENA DE INDIAS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (177, "CICUCO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (178, "CLEMENCIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (179, "CORDOBA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (180, "EL CARMEN DE BOLIVAR"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (181, "EL GUAMO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (182, "EL PENION"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (183, "HATILLO DE LOBA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (184, "MAGANGUE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (185, "MAHATES"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (186, "MARGARITA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (187, "MARIA LA BAJA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (188, "MONTECRISTO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (189, "MORALES"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (190, "MORALES"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (191, "NOROSI"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (192, "PINILLOS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (193, "REGIDOR"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (194, "RIO VIEJO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (195, "SAN CRISTOBAL"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (196, "SAN ESTANISLAO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (197, "SAN FERNANDO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (198, "SAN JACINTO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (199, "SAN JACINTO DEL CAUCA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (200, "SAN JUAN DE NEPOMUCENO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (201, "SAN MARTIN DE LOBA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (202, "SAN PABLO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (203, "SAN PABLO NORTE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (204, "SANTA CATALINA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (205, "SANTA CRUZ DE MOMPOX"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (206, "SANTA ROSA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (207, "SANTA ROSA DEL SUR"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (208, "SIMITI"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (209, "SOPLAVIENTO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (210, "TALAIGUA NUEVO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (211, "TUQUISIO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (212, "TURBACO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (213, "TURBANA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (214, "VILLANUEVA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (215, "ZAMBRANO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (216, "AQUITANIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (217, "ARCABUCO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (218, "BELÉN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (219, "BERBEO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (220, "BETÉITIVA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (221, "BOAVITA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (222, "BOYACÁ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (223, "BRICEÑO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (224, "BUENAVISTA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (225, "BUSBANZÁ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (226, "CALDAS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (227, "CAMPO HERMOSO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (228, "CERINZA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (229, "CHINAVITA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (230, "CHIQUINQUIRÁ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (231, "CHÍQUIZA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (232, "CHISCAS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (233, "CHITA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (234, "CHITARAQUE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (235, "CHIVATÁ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (236, "CIÉNEGA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (237, "CÓMBITA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (238, "COPER"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (239, "CORRALES"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (240, "COVARACHÍA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (241, "CUBARA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (242, "CUCAITA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (243, "CUITIVA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (244, "DUITAMA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (245, "EL COCUY"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (246, "EL ESPINO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (247, "FIRAVITOBA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (248, "FLORESTA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (249, "GACHANTIVÁ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (250, "GÁMEZA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (251, "GARAGOA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (252, "GUACAMAYAS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (253, "GÜICÁN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (254, "IZA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (255, "JENESANO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (256, "JERICÓ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (257, "LA UVITA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (258, "LA VICTORIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (259, "LABRANZA GRANDE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (260, "MACANAL"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (261, "MARIPÍ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (262, "MIRAFLORES"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (263, "MONGUA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (264, "MONGUÍ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (265, "MONIQUIRÁ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (266, "MOTAVITA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (267, "MUZO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (268, "NOBSA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (269, "NUEVO COLÓN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (270, "OICATÁ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (271, "OTANCHE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (272, "PACHAVITA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (273, "PÁEZ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (274, "PAIPA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (275, "PAJARITO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (276, "PANQUEBA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (277, "PAUNA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (278, "PAYA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (279, "PAZ DE RÍO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (280, "PESCA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (281, "PISBA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (282, "PUERTO BOYACA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (283, "QUÍPAMA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (284, "RAMIRIQUÍ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (285, "RÁQUIRA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (286, "RONDÓN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (287, "SABOYÁ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (288, "SÁCHICA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (289, "SAMACÁ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (290, "SAN EDUARDO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (291, "SAN JOSÉ DE PARE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (292, "SAN LUÍS DE GACENO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (293, "SAN MATEO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (294, "SAN MIGUEL DE SEMA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (295, "SAN PABLO DE BORBUR"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (296, "SANTA MARÍA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (297, "SANTA ROSA DE VITERBO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (298, "SANTA SOFÍA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (299, "SANTANA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (300, "SATIVANORTE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (301, "SATIVASUR"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (302, "SIACHOQUE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (303, "SOATÁ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (304, "SOCHA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (305, "SOCOTÁ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (306, "SOGAMOSO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (307, "SORA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (308, "SORACÁ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (309, "SOTAQUIRÁ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (310, "SUSACÓN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (311, "SUTARMACHÁN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (312, "TASCO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (313, "TIBANÁ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (314, "TIBASOSA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (315, "TINJACÁ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (316, "TIPACOQUE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (317, "TOCA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (318, "TOGÜÍ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (319, "TÓPAGA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (320, "TOTA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (321, "TUNJA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (322, "TUNUNGUÁ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (323, "TURMEQUÉ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (324, "TUTA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (325, "TUTAZÁ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (326, "UMBITA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (327, "VENTA QUEMADA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (328, "VILLA DE LEYVA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (329, "VIRACACHÁ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (330, "ZETAQUIRA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (331, "AGUADAS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (332, "ANSERMA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (333, "ARANZAZU"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (334, "BELALCAZAR"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (335, "CHINCHINÁ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (336, "FILADELFIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (337, "LA DORADA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (338, "LA MERCED"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (339, "MANIZALES"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (340, "MANZANARES"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (341, "MARMATO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (342, "MARQUETALIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (343, "MARULANDA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (344, "NEIRA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (345, "NORCASIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (346, "PACORA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (347, "PALESTINA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (348, "PENSILVANIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (349, "RIOSUCIO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (350, "RISARALDA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (351, "SALAMINA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (352, "SAMANA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (353, "SAN JOSE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (354, "SUPÍA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (355, "VICTORIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (356, "VILLAMARÍA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (357, "VITERBO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (358, "ALBANIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (359, "BELÉN ANDAQUIES"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (360, "CARTAGENA DEL CHAIRA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (361, "CURILLO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (362, "EL DONCELLO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (363, "EL PAUJIL"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (364, "FLORENCIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (365, "LA MONTAÑITA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (366, "MILÁN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (367, "MORELIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (368, "PUERTO RICO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (369, "SAN  VICENTE DEL CAGUAN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (370, "SAN JOSÉ DE FRAGUA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (371, "SOLANO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (372, "SOLITA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (373, "VALPARAÍSO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (374, "AGUAZUL"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (375, "CHAMEZA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (376, "HATO COROZAL"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (377, "LA SALINA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (378, "MANÍ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (379, "MONTERREY"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (380, "NUNCHIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (381, "OROCUE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (382, "PAZ DE ARIPORO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (383, "PORE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (384, "RECETOR"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (385, "SABANA LARGA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (386, "SACAMA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (387, "SAN LUIS DE PALENQUE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (388, "TAMARA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (389, "TAURAMENA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (390, "TRINIDAD"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (391, "VILLANUEVA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (392, "YOPAL"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (393, "ALMAGUER"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (394, "ARGELIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (395, "BALBOA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (396, "BOLÍVAR"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (397, "BUENOS AIRES"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (398, "CAJIBIO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (399, "CALDONO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (400, "CALOTO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (401, "CORINTO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (402, "EL TAMBO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (403, "FLORENCIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (404, "GUAPI"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (405, "INZA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (406, "JAMBALÓ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (407, "LA SIERRA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (408, "LA VEGA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (409, "LÓPEZ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (410, "MERCADERES"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (411, "MIRANDA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (412, "MORALES"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (413, "PADILLA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (414, "PÁEZ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (415, "PATIA (EL BORDO)"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (416, "PIAMONTE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (417, "PIENDAMO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (418, "POPAYÁN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (419, "PUERTO TEJADA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (420, "PURACE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (421, "ROSAS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (422, "SAN SEBASTIÁN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (423, "SANTA ROSA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (424, "SANTANDER DE QUILICHAO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (425, "SILVIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (426, "SOTARA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (427, "SUÁREZ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (428, "SUCRE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (429, "TIMBÍO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (430, "TIMBIQUÍ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (431, "TORIBIO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (432, "TOTORO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (433, "VILLA RICA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (434, "AGUACHICA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (435, "AGUSTÍN CODAZZI"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (436, "ASTREA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (437, "BECERRIL"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (438, "BOSCONIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (439, "CHIMICHAGUA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (440, "CHIRIGUANÁ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (441, "CURUMANÍ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (442, "EL COPEY"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (443, "EL PASO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (444, "GAMARRA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (445, "GONZÁLEZ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (446, "LA GLORIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (447, "LA JAGUA IBIRICO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (448, "MANAURE BALCÓN DEL CESAR"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (449, "PAILITAS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (450, "PELAYA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (451, "PUEBLO BELLO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (452, "RÍO DE ORO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (453, "ROBLES (LA PAZ)"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (454, "SAN ALBERTO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (455, "SAN DIEGO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (456, "SAN MARTÍN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (457, "TAMALAMEQUE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (458, "VALLEDUPAR"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (459, "ACANDI"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (460, "ALTO BAUDO (PIE DE PATO)"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (461, "ATRATO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (462, "BAGADO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (463, "BAHIA SOLANO (MUTIS)"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (464, "BAJO BAUDO (PIZARRO)"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (465, "BOJAYA (BELLAVISTA)"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (466, "CANTON DE SAN PABLO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (467, "CARMEN DEL DARIEN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (468, "CERTEGUI"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (469, "CONDOTO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (470, "EL CARMEN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (471, "ISTMINA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (472, "JURADO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (473, "LITORAL DEL SAN JUAN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (474, "LLORO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (475, "MEDIO ATRATO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (476, "MEDIO BAUDO (BOCA DE PEPE)"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (477, "MEDIO SAN JUAN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (478, "NOVITA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (479, "NUQUI"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (480, "QUIBDO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (481, "RIO IRO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (482, "RIO QUITO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (483, "RIOSUCIO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (484, "SAN JOSE DEL PALMAR"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (485, "SIPI"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (486, "TADO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (487, "UNGUIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (488, "UNIÓN PANAMERICANA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (489, "AYAPEL"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (490, "BUENAVISTA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (491, "CANALETE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (492, "CERETÉ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (493, "CHIMA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (494, "CHINÚ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (495, "CIENAGA DE ORO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (496, "COTORRA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (497, "LA APARTADA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (498, "LORICA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (499, "LOS CÓRDOBAS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (500, "MOMIL"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (501, "MONTELÍBANO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (502, "MONTERÍA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (503, "MOÑITOS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (504, "PLANETA RICA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (505, "PUEBLO NUEVO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (506, "PUERTO ESCONDIDO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (507, "PUERTO LIBERTADOR"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (508, "PURÍSIMA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (509, "SAHAGÚN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (510, "SAN ANDRÉS SOTAVENTO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (511, "SAN ANTERO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (512, "SAN BERNARDO VIENTO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (513, "SAN CARLOS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (514, "SAN PELAYO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (515, "TIERRALTA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (516, "VALENCIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (517, "AGUA DE DIOS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (518, "ALBAN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (519, "ANAPOIMA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (520, "ANOLAIMA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (521, "ARBELAEZ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (522, "BELTRÁN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (523, "BITUIMA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (524, "BOGOTÁ DC"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (525, "BOJACÁ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (526, "CABRERA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (527, "CACHIPAY"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (528, "CAJICÁ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (529, "CAPARRAPÍ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (530, "CAQUEZA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (531, "CARMEN DE CARUPA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (532, "CHAGUANÍ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (533, "CHIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (534, "CHIPAQUE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (535, "CHOACHÍ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (536, "CHOCONTÁ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (537, "COGUA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (538, "COTA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (539, "CUCUNUBÁ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (540, "EL COLEGIO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (541, "EL PEÑÓN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (542, "EL ROSAL1"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (543, "FACATATIVA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (544, "FÓMEQUE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (545, "FOSCA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (546, "FUNZA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (547, "FÚQUENE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (548, "FUSAGASUGA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (549, "GACHALÁ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (550, "GACHANCIPÁ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (551, "GACHETA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (552, "GAMA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (553, "GIRARDOT"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (554, "GRANADA2"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (555, "GUACHETÁ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (556, "GUADUAS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (557, "GUASCA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (558, "GUATAQUÍ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (559, "GUATAVITA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (560, "GUAYABAL DE SIQUIMA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (561, "GUAYABETAL"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (562, "GUTIÉRREZ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (563, "JERUSALÉN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (564, "JUNÍN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (565, "LA CALERA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (566, "LA MESA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (567, "LA PALMA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (568, "LA PEÑA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (569, "LA VEGA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (570, "LENGUAZAQUE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (571, "MACHETÁ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (572, "MADRID"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (573, "MANTA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (574, "MEDINA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (575, "MOSQUERA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (576, "NARIÑO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (577, "NEMOCÓN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (578, "NILO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (579, "NIMAIMA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (580, "NOCAIMA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (581, "OSPINA PÉREZ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (582, "PACHO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (583, "PAIME"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (584, "PANDI"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (585, "PARATEBUENO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (586, "PASCA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (587, "PUERTO SALGAR"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (588, "PULÍ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (589, "QUEBRADANEGRA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (590, "QUETAME"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (591, "QUIPILE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (592, "RAFAEL REYES"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (593, "RICAURTE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (594, "SAN  ANTONIO DEL  TEQUENDAMA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (595, "SAN BERNARDO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (596, "SAN CAYETANO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (597, "SAN FRANCISCO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (598, "SAN JUAN DE RIOSECO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (599, "SASAIMA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (600, "SESQUILÉ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (601, "SIBATÉ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (602, "SILVANIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (603, "SIMIJACA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (604, "SOACHA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (605, "SOPO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (606, "SUBACHOQUE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (607, "SUESCA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (608, "SUPATÁ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (609, "SUSA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (610, "SUTATAUSA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (611, "TABIO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (612, "TAUSA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (613, "TENA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (614, "TENJO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (615, "TIBACUY"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (616, "TIBIRITA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (617, "TOCAIMA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (618, "TOCANCIPÁ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (619, "TOPAIPÍ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (620, "UBALÁ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (621, "UBAQUE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (622, "UBATÉ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (623, "UNE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (624, "UTICA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (625, "VERGARA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (626, "VIANI"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (627, "VILLA GOMEZ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (628, "VILLA PINZÓN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (629, "VILLETA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (630, "VIOTA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (631, "YACOPÍ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (632, "ZIPACÓN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (633, "ZIPAQUIRÁ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (634, "BARRANCO MINAS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (635, "CACAHUAL"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (636, "INÍRIDA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (637, "LA GUADALUPE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (638, "MAPIRIPANA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (639, "MORICHAL"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (640, "PANA PANA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (641, "PUERTO COLOMBIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (642, "SAN FELIPE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (643, "CALAMAR"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (644, "EL RETORNO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (645, "MIRAFLOREZ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (646, "SAN JOSÉ DEL GUAVIARE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (647, "ACEVEDO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (648, "AGRADO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (649, "AIPE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (650, "ALGECIRAS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (651, "ALTAMIRA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (652, "BARAYA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (653, "CAMPO ALEGRE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (654, "COLOMBIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (655, "ELIAS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (656, "GARZÓN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (657, "GIGANTE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (658, "GUADALUPE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (659, "HOBO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (660, "IQUIRA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (661, "ISNOS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (662, "LA ARGENTINA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (663, "LA PLATA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (664, "NATAGA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (665, "NEIVA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (666, "OPORAPA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (667, "PAICOL"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (668, "PALERMO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (669, "PALESTINA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (670, "PITAL"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (671, "PITALITO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (672, "RIVERA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (673, "SALADO BLANCO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (674, "SAN AGUSTÍN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (675, "SANTA MARIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (676, "SUAZA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (677, "TARQUI"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (678, "TELLO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (679, "TERUEL"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (680, "TESALIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (681, "TIMANA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (682, "VILLAVIEJA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (683, "YAGUARA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (684, "ALBANIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (685, "BARRANCAS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (686, "DIBULLA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (687, "DISTRACCIÓN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (688, "EL MOLINO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (689, "FONSECA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (690, "HATO NUEVO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (691, "LA JAGUA DEL PILAR"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (692, "MAICAO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (693, "MANAURE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (694, "RIOHACHA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (695, "SAN JUAN DEL CESAR"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (696, "URIBIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (697, "URUMITA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (698, "VILLANUEVA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (699, "ALGARROBO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (700, "ARACATACA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (701, "ARIGUANI"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (702, "CERRO SAN ANTONIO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (703, "CHIVOLO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (704, "CIENAGA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (705, "CONCORDIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (706, "EL BANCO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (707, "EL PIÑON"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (708, "EL RETEN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (709, "FUNDACION"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (710, "GUAMAL"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (711, "NUEVA GRANADA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (712, "PEDRAZA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (713, "PIJIÑO DEL CARMEN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (714, "PIVIJAY"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (715, "PLATO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (716, "PUEBLO VIEJO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (717, "REMOLINO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (718, "SABANAS DE SAN ANGEL"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (719, "SALAMINA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (720, "SAN SEBASTIAN DE BUENAVISTA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (721, "SAN ZENON"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (722, "SANTA ANA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (723, "SANTA BARBARA DE PINTO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (724, "SANTA MARTA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (725, "SITIONUEVO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (726, "TENERIFE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (727, "ZAPAYAN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (728, "ZONA BANANERA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (729, "ACACIAS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (730, "BARRANCA DE UPIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (731, "CABUYARO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (732, "CASTILLA LA NUEVA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (733, "CUBARRAL"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (734, "CUMARAL"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (735, "EL CALVARIO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (736, "EL CASTILLO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (737, "EL DORADO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (738, "FUENTE DE ORO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (739, "GRANADA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (740, "GUAMAL"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (741, "LA MACARENA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (742, "LA URIBE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (743, "LEJANÍAS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (744, "MAPIRIPÁN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (745, "MESETAS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (746, "PUERTO CONCORDIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (747, "PUERTO GAITÁN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (748, "PUERTO LLERAS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (749, "PUERTO LÓPEZ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (750, "PUERTO RICO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (751, "RESTREPO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (752, "SAN  JUAN DE ARAMA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (753, "SAN CARLOS GUAROA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (754, "SAN JUANITO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (755, "SAN MARTÍN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (756, "VILLAVICENCIO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (757, "VISTA HERMOSA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (758, "ALBAN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (759, "ALDAÑA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (760, "ANCUYA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (761, "ARBOLEDA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (762, "BARBACOAS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (763, "BELEN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (764, "BUESACO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (765, "CHACHAGUI"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (766, "COLON (GENOVA)"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (767, "CONSACA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (768, "CONTADERO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (769, "CORDOBA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (770, "CUASPUD"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (771, "CUMBAL"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (772, "CUMBITARA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (773, "EL CHARCO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (774, "EL PEÑOL"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (775, "EL ROSARIO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (776, "EL TABLÓN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (777, "EL TAMBO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (778, "FUNES"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (779, "GUACHUCAL"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (780, "GUAITARILLA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (781, "GUALMATAN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (782, "ILES"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (783, "IMUES"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (784, "IPIALES"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (785, "LA CRUZ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (786, "LA FLORIDA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (787, "LA LLANADA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (788, "LA TOLA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (789, "LA UNION"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (790, "LEIVA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (791, "LINARES"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (792, "LOS ANDES"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (793, "MAGUI"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (794, "MALLAMA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (795, "MOSQUEZA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (796, "NARIÑO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (797, "OLAYA HERRERA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (798, "OSPINA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (799, "PASTO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (800, "PIZARRO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (801, "POLICARPA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (802, "POTOSI"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (803, "PROVIDENCIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (804, "PUERRES"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (805, "PUPIALES"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (806, "RICAURTE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (807, "ROBERTO PAYAN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (808, "SAMANIEGO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (809, "SAN BERNARDO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (810, "SAN LORENZO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (811, "SAN PABLO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (812, "SAN PEDRO DE CARTAGO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (813, "SANDONA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (814, "SANTA BARBARA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (815, "SANTACRUZ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (816, "SAPUYES"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (817, "TAMINANGO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (818, "TANGUA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (819, "TUMACO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (820, "TUQUERRES"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (821, "YACUANQUER"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (822, "ABREGO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (823, "ARBOLEDAS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (824, "BOCHALEMA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (825, "BUCARASICA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (826, "CÁCHIRA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (827, "CÁCOTA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (828, "CHINÁCOTA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (829, "CHITAGÁ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (830, "CONVENCIÓN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (831, "CÚCUTA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (832, "CUCUTILLA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (833, "DURANIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (834, "EL CARMEN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (835, "EL TARRA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (836, "EL ZULIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (837, "GRAMALOTE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (838, "HACARI"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (839, "HERRÁN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (840, "LA ESPERANZA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (841, "LA PLAYA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (842, "LABATECA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (843, "LOS PATIOS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (844, "LOURDES"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (845, "MUTISCUA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (846, "OCAÑA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (847, "PAMPLONA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (848, "PAMPLONITA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (849, "PUERTO SANTANDER"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (850, "RAGONVALIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (851, "SALAZAR"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (852, "SAN CALIXTO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (853, "SAN CAYETANO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (854, "SANTIAGO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (855, "SARDINATA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (856, "SILOS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (857, "TEORAMA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (858, "TIBÚ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (859, "TOLEDO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (860, "VILLA CARO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (861, "VILLA DEL ROSARIO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (862, "COLÓN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (863, "MOCOA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (864, "ORITO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (865, "PUERTO ASÍS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (866, "PUERTO CAYCEDO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (867, "PUERTO GUZMÁN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (868, "PUERTO LEGUÍZAMO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (869, "SAN FRANCISCO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (870, "SAN MIGUEL"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (871, "SANTIAGO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (872, "SIBUNDOY"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (873, "VALLE DEL GUAMUEZ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (874, "VILLAGARZÓN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (875, "ARMENIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (876, "BUENAVISTA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (877, "CALARCÁ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (878, "CIRCASIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (879, "CÓRDOBA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (880, "FILANDIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (881, "GÉNOVA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (882, "LA TEBAIDA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (883, "MONTENEGRO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (884, "PIJAO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (885, "QUIMBAYA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (886, "SALENTO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (887, "APIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (888, "BALBOA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (889, "BELÉN DE UMBRÍA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (890, "DOS QUEBRADAS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (891, "GUATICA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (892, "LA CELIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (893, "LA VIRGINIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (894, "MARSELLA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (895, "MISTRATO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (896, "PEREIRA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (897, "PUEBLO RICO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (898, "QUINCHÍA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (899, "SANTA ROSA DE CABAL"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (900, "SANTUARIO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (901, "PROVIDENCIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (902, "SAN ANDRES"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (903, "SANTA CATALINA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (904, "AGUADA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (905, "ALBANIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (906, "ARATOCA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (907, "BARBOSA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (908, "BARICHARA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (909, "BARRANCABERMEJA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (910, "BETULIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (911, "BOLÍVAR"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (912, "BUCARAMANGA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (913, "CABRERA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (914, "CALIFORNIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (915, "CAPITANEJO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (916, "CARCASI"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (917, "CEPITA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (918, "CERRITO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (919, "CHARALÁ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (920, "CHARTA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (921, "CHIMA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (922, "CHIPATÁ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (923, "CIMITARRA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (924, "CONCEPCIÓN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (925, "CONFINES"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (926, "CONTRATACIÓN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (927, "COROMORO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (928, "CURITÍ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (929, "EL CARMEN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (930, "EL GUACAMAYO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (931, "EL PEÑÓN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (932, "EL PLAYÓN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (933, "ENCINO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (934, "ENCISO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (935, "FLORIÁN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (936, "FLORIDABLANCA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (937, "GALÁN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (938, "GAMBITA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (939, "GIRÓN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (940, "GUACA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (941, "GUADALUPE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (942, "GUAPOTA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (943, "GUAVATÁ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (944, "GUEPSA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (945, "HATO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (946, "JESÚS MARIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (947, "JORDÁN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (948, "LA BELLEZA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (949, "LA PAZ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (950, "LANDAZURI"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (951, "LEBRIJA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (952, "LOS SANTOS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (953, "MACARAVITA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (954, "MÁLAGA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (955, "MATANZA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (956, "MOGOTES"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (957, "MOLAGAVITA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (958, "OCAMONTE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (959, "OIBA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (960, "ONZAGA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (961, "PALMAR"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (962, "PALMAS DEL SOCORRO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (963, "PÁRAMO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (964, "PIEDECUESTA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (965, "PINCHOTE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (966, "PUENTE NACIONAL"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (967, "PUERTO PARRA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (968, "PUERTO WILCHES"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (969, "RIONEGRO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (970, "SABANA DE TORRES"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (971, "SAN ANDRÉS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (972, "SAN BENITO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (973, "SAN GIL"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (974, "SAN JOAQUÍN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (975, "SAN JOSÉ DE MIRANDA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (976, "SAN MIGUEL"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (977, "SAN VICENTE DE CHUCURÍ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (978, "SANTA BÁRBARA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (979, "SANTA HELENA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (980, "SIMACOTA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (981, "SOCORRO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (982, "SUAITA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (983, "SUCRE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (984, "SURATA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (985, "TONA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (986, "VALLE SAN JOSÉ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (987, "VÉLEZ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (988, "VETAS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (989, "VILLANUEVA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (990, "ZAPATOCA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (991, "BUENAVISTA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (992, "CAIMITO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (993, "CHALÁN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (994, "COLOSO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (995, "COROZAL"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (996, "EL ROBLE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (997, "GALERAS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (998, "GUARANDA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (999, "LA UNIÓN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1000, "LOS PALMITOS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1001, "MAJAGUAL"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1002, "MORROA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1003, "OVEJAS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1004, "PALMITO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1005, "SAMPUES"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1006, "SAN BENITO ABAD"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1007, "SAN JUAN DE BETULIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1008, "SAN MARCOS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1009, "SAN ONOFRE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1010, "SAN PEDRO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1011, "SINCÉ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1012, "SINCELEJO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1013, "SUCRE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1014, "TOLÚ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1015, "TOLUVIEJO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1016, "ALPUJARRA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1017, "ALVARADO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1018, "AMBALEMA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1019, "ANZOATEGUI"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1020, "ARMERO (GUAYABAL)"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1021, "ATACO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1022, "CAJAMARCA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1023, "CARMEN DE APICALÁ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1024, "CASABIANCA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1025, "CHAPARRAL"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1026, "COELLO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1027, "COYAIMA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1028, "CUNDAY"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1029, "DOLORES"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1030, "ESPINAL"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1031, "FALÁN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1032, "FLANDES"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1033, "FRESNO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1034, "GUAMO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1035, "HERVEO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1036, "HONDA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1037, "IBAGUÉ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1038, "ICONONZO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1039, "LÉRIDA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1040, "LÍBANO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1041, "MARIQUITA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1042, "MELGAR"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1043, "MURILLO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1044, "NATAGAIMA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1045, "ORTEGA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1046, "PALOCABILDO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1047, "PIEDRAS PLANADAS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1048, "PRADO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1049, "PURIFICACIÓN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1050, "RIOBLANCO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1051, "RONCESVALLES"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1052, "ROVIRA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1053, "SALDAÑA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1054, "SAN ANTONIO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1055, "SAN LUIS"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1056, "SANTA ISABEL"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1057, "SUÁREZ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1058, "VALLE DE SAN JUAN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1059, "VENADILLO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1060, "VILLAHERMOSA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1061, "VILLARRICA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1062, "ALCALÁ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1063, "ANDALUCÍA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1064, "ANSERMA NUEVO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1065, "ARGELIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1066, "BOLÍVAR"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1067, "BUENAVENTURA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1068, "BUGA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1069, "BUGALAGRANDE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1070, "CAICEDONIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1071, "CALI"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1072, "CALIMA (DARIEN)"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1073, "CANDELARIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1074, "CARTAGO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1075, "DAGUA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1076, "EL AGUILA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1077, "EL CAIRO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1078, "EL CERRITO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1079, "EL DOVIO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1080, "FLORIDA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1081, "GINEBRA GUACARI"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1082, "JAMUNDÍ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1083, "LA CUMBRE"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1084, "LA UNIÓN"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1085, "LA VICTORIA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1086, "OBANDO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1087, "PALMIRA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1088, "PRADERA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1089, "RESTREPO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1090, "RIO FRÍO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1091, "ROLDANILLO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1092, "SAN PEDRO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1093, "SEVILLA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1094, "TORO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1095, "TRUJILLO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1096, "TULÚA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1097, "ULLOA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1098, "VERSALLES"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1099, "VIJES"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1100, "YOTOCO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1101, "YUMBO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1102, "ZARZAL"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1103, "CARURÚ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1104, "MITÚ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1105, "PACOA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1106, "PAPUNAUA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1107, "TARAIRA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1108, "YAVARATÉ"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1109, "CUMARIBO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1110, "LA PRIMAVERA"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1111, "PUERTO CARREÑO"); 
INSERT INTO municipio (id_muni, nam_muni) VALUES (1112, "SANTA ROSALIA"); 

