INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1,1); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (2,1); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (3,1); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (4,1); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (5,1); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (6,1); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (7,1); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (8,1); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (9,1); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (10,1); 
/*INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (11,1); */
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (12,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (13,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (14,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (15,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (16,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (17,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (18,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (19,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (20,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (21,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (22,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (23,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (24,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (25,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (26,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (27,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (28,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (29,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (30,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (31,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (32,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (33,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (34,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (35,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (36,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (37,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (38,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (39,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (40,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (41,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (42,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (43,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (44,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (45,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (46,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (47,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (48,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (49,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (50,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (51,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (52,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (53,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (54,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (55,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (56,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (57,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (58,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (59,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (60,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (61,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (62,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (63,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (64,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (65,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (66,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (67,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (68,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (69,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (70,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (71,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (72,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (73,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (74,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (75,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (76,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (77,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (78,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (79,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (80,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (81,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (82,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (83,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (84,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (85,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (86,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (87,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (88,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (89,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (90,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (91,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (92,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (93,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (94,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (95,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (96,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (97,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (98,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (99,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (100,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (101,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (102,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (103,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (104,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (105,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (106,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (107,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (108,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (109,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (110,2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (111, 2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (112, 2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (113, 2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (114, 2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (115, 2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (116, 2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (117, 2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (118, 2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (119, 2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (120, 2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (121, 2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (122, 2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (123, 2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (124, 2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (125, 2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (126, 2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (127, 2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (128, 2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (129, 2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (130, 2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (131, 2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (132, 2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (133, 2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (134, 2); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (135, 2); 
/*INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (136, 2); */
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (137, ARAUCA, 3); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (138, ARAUQUITA, 3); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (139, CRAVO NORTE, 3); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (140, FORTUL, 3); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (141, PUERTO RONDON, 3); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (142, SARAVENA, 3); 
/*INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (143, TAME, 3); */
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (144, BARANOA, 4); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (145, BARRANQUILLA, 4); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (146, CAMPO DE LA CRUZ, 4); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (147, CANDELARIA, 4); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (148, GALAPA, 4); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (149, JUAN DE ACOSTA, 4); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (150, LURUACO, 4); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (151, MALAMBO, 4); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (152, MANATI, 4); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (153, PALMAR DE VARELA, 4); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (154, PIOJO, 4); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (155, POLO NUEVO, 4); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (156, PONEDERA, 4); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (157, PUERTO COLOMBIA, 4); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (158, REPELON, 4); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (159, SABANAGRANDE, 4); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (160, SABANALARGA, 4); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (161, A LUCIA, 4); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (162, O TOMAS, 4); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (163, SOLEDAD, 4); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (164, SUAN, 4); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (165, TUBARA, 4); 
/*INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (166, USIACURI, 4); */
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (167, ACHI, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (168, ALTOS DEL ROSARIO, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (169, ARENAL, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (170, ARJONA, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (171, ARROYOHONDO, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (172, BARRANCO DE LOBA, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (173, BRAZUELO DE PAPAYAL, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (174, CALAMAR, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (175, CANTAGALLO, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (176, CARTAGENA DE INDIAS, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (177, CICUCO, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (178, CLEMENCIA, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (179, CORDOBA, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (180, EL CARMEN DE BOLIVAR, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (181, EL GUAMO, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (182, EL PENION, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (183, HATILLO DE LOBA, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (184, MAGANGUE, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (185, MAHATES, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (186, MARGARITA, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (187, MARIA LA BAJA, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (188, MONTECRISTO, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (189, MORALES, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (190, MORALES, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (191, NOROSI, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (192, PINILLOS, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (193, REGIDOR, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (194, RIO VIEJO, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (195, SAN CRISTOBAL, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (196, SAN ESTANISLAO, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (197, SAN FERNANDO, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (198, SAN JACINTO, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (199, SAN JACINTO DEL CAUCA, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (200, SAN JUAN DE NEPOMUCENO, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (201, SAN MARTIN DE LOBA, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (202, SAN PABLO, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (203, SAN PABLO NORTE, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (204, A CATALINA, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (205, A CRUZ DE MOMPOX, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (206, A ROSA, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (207,L SUR, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (208, SIMITI, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (209, SOPLAVIENTO, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (210, TALAIGUA NUEVO, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (211, TUQUISIO, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (212, TURBACO, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (213, TURBANA, 5); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (214, VILLANUEVA, 5); 
/*INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (215, ZAMBRANO, 5);*/ 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (216, AQUITANIA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (217, ARCABUCO, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (218, BELÉN, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (219, BERBEO, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (220, BETÉITIVA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (221, BOAVITA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (222, BOYACÁ, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (223, BRICEÑO, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (224, BUENAVISTA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (225, BUSBANZÁ, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (226, CALDAS, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (227, CAMPO HERMOSO, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (228, CERINZA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (229, CHINAVITA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (230, CHIQUINQUIRÁ, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (231, CHÍQUIZA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (232, CHISCAS, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (233, CHITA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (234, CHITARAQUE, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (235, CHIVATÁ, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (236, CIÉNEGA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (237, CÓMBITA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (238, COPER, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (239, CORRALES, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (240, COVARACHÍA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (241, CUBARA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (242, CUCAITA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (243, CUITIVA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (244, DUITAMA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (245, EL COCUY, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (246, EL ESPINO, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (247, FIRAVITOBA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (248, FLORESTA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (249, GACHANTIVÁ, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (250, GÁMEZA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (251, GARAGOA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (252, GUACAMAYAS, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (253, GÜICÁN, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (254, IZA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (255, JENESANO, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (256, JERICÓ, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (257, LA UVITA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (258, LA VICTORIA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (259, LABRANZA GRANDE, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (260, MACANAL, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (261, MARIPÍ, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (262, MIRAFLORES, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (263, MONGUA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (264, MONGUÍ, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (265, MONIQUIRÁ, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (266, MOTAVITA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (267, MUZO, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (268, NOBSA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (269, NUEVO COLÓN, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (270, OICATÁ, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (271, OTANCHE, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (272, PACHAVITA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (273, PÁEZ, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (274, PAIPA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (275, PAJARITO, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (276, PANQUEBA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (277, PAUNA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (278, PAYA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (279, PAZ DE RÍO, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (280, PESCA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (281, PISBA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (282, PUERTO BOYACA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (283, QUÍPAMA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (284, RAMIRIQUÍ, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (285, RÁQUIRA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (286, RONDÓN, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (287, SABOYÁ, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (288, SÁCHICA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (289, SAMACÁ, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (290, SAN EDUARDO, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (291, SAN JOSÉ DE PARE, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (292, SAN LUÍS DE GACENO, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (293, SAN MATEO, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (294, SAN MIGUEL DE SEMA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (295, SAN PABLO DE BORBUR, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (296, A MARÍA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (297, VITERBO, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (298, A SOFÍA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (299, ANA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (300, SATIVANORTE, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (301, SATIVASUR, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (302, SIACHOQUE, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (303, SOATÁ, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (304, SOCHA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (305, SOCOTÁ, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (306, SOGAMOSO, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (307, SORA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (308, SORACÁ, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (309, SOTAQUIRÁ, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (310, SUSACÓN, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (311, SUTARMACHÁN, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (312, TASCO, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (313, TIBANÁ, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (314, TIBASOSA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (315, TINJACÁ, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (316, TIPACOQUE, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (317, TOCA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (318, TOGÜÍ, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (319, TÓPAGA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (320, TOTA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (321, TUNJA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (322, TUNUNGUÁ, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (323, TURMEQUÉ, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (324, TUTA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (325, TUTAZÁ, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (326, UMBITA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (327, VENTA QUEMADA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (328, VILLA DE LEYVA, 6); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (329, VIRACACHÁ, 6); 
/*INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (330, ZETAQUIRA, 6);*/ 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (331, AGUADAS, 7); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (332, ANSERMA, 7); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (333, ARANZAZU, 7); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (334, BELALCAZAR, 7); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (335, CHINCHINÁ, 7); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (336, FILADELFIA, 7); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (337, LA DORADA, 7); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (338, LA MERCED, 7); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (339, MANIZALES, 7); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (340, MANZANARES, 7); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (341, MARMATO, 7); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (342, MARQUETALIA, 7); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (343, MARULANDA, 7); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (344, NEIRA, 7); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (345, NORCASIA, 7); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (346, PACORA, 7); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (347, PALESTINA, 7); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (348, PENSILVANIA, 7); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (349, RIOSUCIO, 7); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (350, RISARALDA, 7); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (351, SALAMINA, 7); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (352, SAMANA, 7); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (353, SAN JOSE, 7); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (354, SUPÍA, 7); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (355, VICTORIA, 7); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (356, VILLAMARÍA, 7); 
/*INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (357, VITERBO, 7); */
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (358, ALBANIA, 8); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (359, BELÉN ANDAQUIES, 8); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (360, CARTAGENA DEL CHAIRA, 8); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (361, CURILLO, 8); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (362, EL DONCELLO, 8); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (363, EL PAUJIL, 8); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (364, FLORENCIA, 8); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (365, LA MONTAÑITA, 8); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (366, MILÁN, 8); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (367, MORELIA, 8); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (368, PUERTO RICO, 8); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (369, SAN  VICENTE DEL CAGUAN, 8); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (370, SAN JOSÉ DE FRAGUA, 8); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (371, SOLANO, 8); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (372, SOLITA, 8); 
/*INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (373, VALPARAÍSO, 8); */
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (374, AGUAZUL, 9); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (375, CHAMEZA, 9); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (376, HATO COROZAL, 9); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (377, LA SALINA, 9); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (378, MANÍ, 9); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (379, MONTERREY, 9); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (380, NUNCHIA, 9); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (381, OROCUE, 9); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (382, PAZ DE ARIPORO, 9); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (383, PORE, 9); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (384, RECETOR, 9); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (385, SABANA LARGA, 9); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (386, SACAMA, 9); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (387, SAN LUIS DE PALENQUE, 9); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (388, TAMARA, 9); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (389, TAURAMENA, 9); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (390, TRINIDAD, 9); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (391, VILLANUEVA, 9); 
/*INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (392, YOPAL, 9); */
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (393, ALMAGUER, 10); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (394, ARGELIA, 10); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (395, BALBOA, 10); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (396, BOLÍVAR, 10); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (397, BUENOS AIRES, 10); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (398, CAJIBIO, 10); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (399, CALDONO, 10); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (400, CALOTO, 10); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (401, CORINTO, 10); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (402, EL TAMBO, 10); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (403, FLORENCIA, 10); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (404, GUAPI, 10); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (405, INZA, 10); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (406, JAMBALÓ, 10); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (407, LA SIERRA, 10); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (408, LA VEGA, 10); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (409, LÓPEZ, 10); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (410, MERCADERES, 10); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (411, MIRANDA, 10); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (412, MORALES, 10); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (413, PADILLA, 10); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (414, PÁEZ, 10); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (415, PATIA (EL BORDO), 10); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (416, PIAMONTE, 10); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (417, PIENDAMO, 10); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (418, POPAYÁN, 10); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (419, PUERTO TEJADA, 10); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (420, PURACE, 10); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (421, ROSAS, 10); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (422, SAN SEBASTIÁN, 10); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (423, A ROSA, 10); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (424, ANDER DE QUILICHAO, 10); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (425, SILVIA, 10); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (426, SOTARA, 10); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (427, SUÁREZ, 10); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (428, SUCRE, 10); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (429, TIMBÍO, 10); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (430, TIMBIQUÍ, 10); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (431, TORIBIO, 10); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (432, TOTORO, 10); 
/*INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (433, VILLA RICA, 10); */
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (434, AGUACHICA, 11); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (435, AGUSTÍN CODAZZI, 11); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (436, ASTREA, 11); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (437, BECERRIL, 11); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (438, BOSCONIA, 11); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (439, CHIMICHAGUA, 11); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (440, CHIRIGUANÁ, 11); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (441, CURUMANÍ, 11); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (442, EL COPEY, 11); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (443, EL PASO, 11); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (444, GAMARRA, 11); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (445, GONZÁLEZ, 11); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (446, LA GLORIA, 11); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (447, LA JAGUA IBIRICO, 11); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (448, MANAURE BALCÓN DEL CESAR, 11); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (449, PAILITAS, 11); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (450, PELAYA, 11); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (451, PUEBLO BELLO, 11); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (452, RÍO DE ORO, 11); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (453, ROBLES (LA PAZ), 11); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (454, SAN ALBERTO, 11); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (455, SAN DIEGO, 11); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (456, SAN MARTÍN, 11); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (457, TAMALAMEQUE, 11); 
/*INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (458, VALLEDUPAR, 11); */
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (459, ACANDI, 12); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (460, ALTO BAUDO (PIE DE PATO), 12); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (461, ATRATO, 12); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (462, BAGADO, 12); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (463, BAHIA SOLANO (MUTIS), 12); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (464, BAJO BAUDO (PIZARRO), 12); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (465, BOJAYA (BELLAVISTA), 12); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (466, CANTON DE SAN PABLO, 12); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (467, CARMEN DEL DARIEN, 12); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (468, CERTEGUI, 12); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (469, CONDOTO, 12); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (470, EL CARMEN, 12); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (471, ISTMINA, 12); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (472, JURADO, 12); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (473, LITORAL DEL SAN JUAN, 12); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (474, LLORO, 12); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (475, MEDIO ATRATO, 12); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (476, MEDIO BAUDO (BOCA DE PEPE), 12); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (477, MEDIO SAN JUAN, 12); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (478, NOVITA, 12); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (479, NUQUI, 12); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (480, QUIBDO, 12); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (481, RIO IRO, 12); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (482, RIO QUITO, 12); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (483, RIOSUCIO, 12); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (484, SAN JOSE DEL PALMAR, 12); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (485, SIPI, 12); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (486, TADO, 12); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (487, UNGUIA, 12); 
/*INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (488, UNIÓN PANAMERICANA, 12); */
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (489, AYAPEL, 13); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (490, BUENAVISTA, 13); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (491, CANALETE, 13); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (492, CERETÉ, 13); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (493, CHIMA, 13); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (494, CHINÚ, 13); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (495, CIENAGA DE ORO, 13); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (496, COTORRA, 13); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (497, LA APARTADA, 13); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (498, LORICA, 13); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (499, LOS CÓRDOBAS, 13); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (500, MOMIL, 13); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (501, MONTELÍBANO, 13); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (502, MONTERÍA, 13); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (503, MOÑITOS, 13); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (504, PLANETA RICA, 13); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (505, PUEBLO NUEVO, 13); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (506, PUERTO ESCONDIDO, 13); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (507, PUERTO LIBERTADOR, 13); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (508, PURÍSIMA, 13); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (509, SAHAGÚN, 13); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (510, SAN ANDRÉS SOTAVENTO, 13); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (511, SAN ANTERO, 13); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (512, SAN BERNARDO VIENTO, 13); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (513, SAN CARLOS, 13); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (514, SAN PELAYO, 13); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (515, TIERRALTA, 13); 
/*INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (516, VALENCIA, 13); */
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (517, AGUA DE DIOS, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (518, ALBAN, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (519, ANAPOIMA, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (520, ANOLAIMA, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (521, ARBELAEZ, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (522, BELTRÁN, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (523, BITUIMA, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (524, BOGOTÁ DC, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (525, BOJACÁ, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (526, CABRERA, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (527, CACHIPAY, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (528, CAJICÁ, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (529, CAPARRAPÍ, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (530, CAQUEZA, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (531, CARMEN DE CARUPA, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (532, CHAGUANÍ, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (533, CHIA, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (534, CHIPAQUE, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (535, CHOACHÍ, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (536, CHOCONTÁ, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (537, COGUA, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (538, COTA, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (539, CUCUNUBÁ, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (540, EL COLEGIO, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (541, EL PEÑÓN, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (542, EL ROSAL1, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (543, FACATATIVA, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (544, FÓMEQUE, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (545, FOSCA, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (546, FUNZA, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (547, FÚQUENE, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (548, FUSAGASUGA, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (549, GACHALÁ, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (550, GACHANCIPÁ, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (551, GACHETA, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (552, GAMA, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (553, GIRARDOT, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (554, GRANADA2, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (555, GUACHETÁ, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (556, GUADUAS, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (557, GUASCA, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (558, GUATAQUÍ, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (559, GUATAVITA, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (560, GUAYABAL DE SIQUIMA, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (561, GUAYABETAL, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (562, GUTIÉRREZ, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (563, JERUSALÉN, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (564, JUNÍN, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (565, LA CALERA, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (566, LA MESA, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (567, LA PALMA, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (568, LA PEÑA, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (569, LA VEGA, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (570, LENGUAZAQUE, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (571, MACHETÁ, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (572, MADRID, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (573, MANTA, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (574, MEDINA, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (575, MOSQUERA, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (576, NARIÑO, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (577, NEMOCÓN, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (578, NILO, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (579, NIMAIMA, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (580, NOCAIMA, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (581, OSPINA PÉREZ, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (582, PACHO, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (583, PAIME, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (584, PANDI, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (585, PARATEBUENO, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (586, PASCA, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (587, PUERTO SALGAR, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (588, PULÍ, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (589, QUEBRADANEGRA, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (590, QUETAME, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (591, QUIPILE, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (592, RAFAEL REYES, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (593, RICAURTE, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (594, SAN  ANTONIO DEL  TEQUENDAMA, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (595, SAN BERNARDO, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (596, SAN CAYETANO, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (597, SAN FRANCISCO, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (598, SAN JUAN DE RIOSECO, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (599, SASAIMA, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (600, SESQUILÉ, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (601, SIBATÉ, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (602, SILVANIA, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (603, SIMIJACA, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (604, SOACHA, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (605, SOPO, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (606, SUBACHOQUE, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (607, SUESCA, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (608, SUPATÁ, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (609, SUSA, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (610, SUTATAUSA, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (611, TABIO, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (612, TAUSA, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (613, TENA, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (614, TENJO, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (615, TIBACUY, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (616, TIBIRITA, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (617, TOCAIMA, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (618, TOCANCIPÁ, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (619, TOPAIPÍ, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (620, UBALÁ, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (621, UBAQUE, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (622, UBATÉ, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (623, UNE, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (624, UTICA, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (625, VERGARA, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (626, VIANI, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (627, VILLA GOMEZ, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (628, VILLA PINZÓN, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (629, VILLETA, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (630, VIOTA, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (631, YACOPÍ, 14); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (632, ZIPACÓN, 14); 
/*INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (633, ZIPAQUIRÁ, 14); */
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (634, BARRANCO MINAS, 15); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (635, CACAHUAL, 15); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (636, INÍRIDA, 15); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (637, LA GUADALUPE, 15); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (638, MAPIRIPANA, 15); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (639, MORICHAL, 15); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (640, PANA PANA, 15); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (641, PUERTO COLOMBIA, 15); 
/*INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (642, SAN FELIPE, 15); */
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (643, CALAMAR, 16); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (644, EL RETORNO, 16); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (645, MIRAFLOREZ, 16); 
/*INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (646, SAN JOSÉ DEL GUAVIARE, 16); */
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (647, ACEVEDO, 17); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (648, AGRADO, 17); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (649, AIPE, 17); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (650, ALGECIRAS, 17); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (651, ALTAMIRA, 17); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (652, BARAYA, 17); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (653, CAMPO ALEGRE, 17); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (654, COLOMBIA, 17); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (655, ELIAS, 17); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (656, GARZÓN, 17); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (657, GIGANTE, 17); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (658, GUADALUPE, 17); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (659, HOBO, 17); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (660, IQUIRA, 17); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (661, ISNOS, 17); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (662, LA ARGENTINA, 17); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (663, LA PLATA, 17); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (664, NATAGA, 17); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (665, NEIVA, 17); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (666, OPORAPA, 17); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (667, PAICOL, 17); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (668, PALERMO, 17); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (669, PALESTINA, 17); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (670, PITAL, 17); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (671, PITALITO, 17); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (672, RIVERA, 17); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (673, SALADO BLANCO, 17); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (674, SAN AGUSTÍN, 17); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (675, A MARIA, 17); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (676, SUAZA, 17); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (677, TARQUI, 17); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (678, TELLO, 17); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (679, TERUEL, 17); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (680, TESALIA, 17); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (681, TIMANA, 17); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (682, VILLAVIEJA, 17); 
/*INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (683, YAGUARA, 17); */
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (684, ALBANIA, 18); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (685, BARRANCAS, 18); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (686, DIBULLA, 18); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (687, DISTRACCIÓN, 18); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (688, EL MOLINO, 18); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (689, FONSECA, 18); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (690, HATO NUEVO, 18); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (691, LA JAGUA DEL PILAR, 18); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (692, MAICAO, 18); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (693, MANAURE, 18); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (694, RIOHACHA, 18); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (695, SAN JUAN DEL CESAR, 18); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (696, URIBIA, 18); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (697, URUMITA, 18); 
/*INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (698, VILLANUEVA, 18); */
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (699, ALGARROBO, 19); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (700, ARACATACA, 19); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (701, ARIGUANI, 19); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (702, CERRO SAN ANTONIO, 19); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (703, CHIVOLO, 19); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (704, CIENAGA, 19); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (705, CONCORDIA, 19); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (706, EL BANCO, 19); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (707, EL PIÑON, 19); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (708, EL RETEN, 19); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (709, FUNDACION, 19); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (710, GUAMAL, 19); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (711, NUEVA GRANADA, 19); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (712, PEDRAZA, 19); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (713, PIJIÑO DEL CARMEN, 19); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (714, PIVIJAY, 19); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (715, PLATO, 19); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (716, PUEBLO VIEJO, 19); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (717, REMOLINO, 19); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (718, SABANAS DE SAN ANGEL, 19); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (719, SALAMINA, 19); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (720, SAN SEBASTIAN DE BUENAVISTA, 19); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (721, SAN ZENON, 19); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (722, A ANA, 19); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (723, RBARA DE PINTO, 19); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (724, A MARTA, 19); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (725, SITIONUEVO, 19); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (726, TENERIFE, 19); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (727, ZAPAYAN, 19); 
/*INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (728, ZONA BANANERA, 19); */
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (729, AC 20); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (730, BARRANCA DE 20); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (731, CAB 20); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (732, CASTILLA LA  20); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (733, CUB 20); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (734, CU 20); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (735, EL CAL 20); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (736, EL CAS 20); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (737, EL D 20); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (738, FUENTE D 20); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (739, GR 20); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (740, G 20); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (741, LA MAC 20); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (742, LA  20); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (743, LEJ 20); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (744, MAPI 20); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (745, ME 20); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (746, PUERTO CONC 20); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (747, PUERTO G 20); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (748, PUERTO L 20); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (749, PUERTO  20); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (750, PUERTO 20); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (751, RES 20); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (752, SAN  JUAN DE  20); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (753, SAN CARLOS G 20); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (754, SAN JU 20); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (755, SAN M 20); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (756, VILLAVIC 20); 
/*INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (757, VISTA HE 20); */
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (758,  21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (759, A 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (760, A 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (761, ARB 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (762, BARB 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (763,  21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (764, BU 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (765, CHAC 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (766, COLON (GE 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (767, CO 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (768, CONT 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (769, CO 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (770, CU 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (771, C 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (772, CUMB 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (773, EL C 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (774, EL  21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (775, EL RO 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (776, EL T 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (777, EL  21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (778,  21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (779, GUAC 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (780, GUAITA 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (781, GUAL 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (782, 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (783,  21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (784, IP 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (785, LA 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (786, LA FL 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (787, LA LL 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (788, LA 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (789, LA  21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (790,  21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (791, LI 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (792, LOS  21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (793,  21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (794, MA 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (795, MOS 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (796, N 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (797, OLAYA HE 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (798, O 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (799,  21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (800, PI 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (801, POLI 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (802, P 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (803, PROVID 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (804, PU 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (805, PUP 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (806, RIC 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (807, ROBERTO  21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (808, SAMA 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (809, SAN BER 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (810, SAN LO 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (811, SAN  21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (812, SAN PEDRO DE CA 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (813, SA 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (814,  21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (815,  21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (816, SA 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (817, TAMI 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (818, T 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (819, T 21); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (820, TUQU 21); 
/*INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (821, YACUA 21); */
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (822, A 22); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (823, ARBO 22); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (824, BOCH 22); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (825, BUCAR 22); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (826, CÁ 22); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (827, C 22); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (828, CHIN 22); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (829, CH 22); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (830, CONVE 22); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (831, C 22); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (832, CUCU 22); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (833, DU 22); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (834, EL C 22); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (835, EL  22); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (836, EL  22); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (837, GRAM 22); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (838, H 22); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (839, H 22); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (840, LA ESPE 22); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (841, LA  22); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (842, LAB 22); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (843, LOS P 22); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (844, LO 22); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (845, MUT 22); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (846,  22); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (847, PAM 22); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (848, PAMPL 22); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (849, PUERTO  22); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (850, RAGON 22); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (851, SA 22); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (852, SAN CA 22); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (853, SAN CAY 22); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (854, SAN 22); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (855, SARD 22); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (856,  22); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (857, TE 22); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (858, 22); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (859, T 22); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (860, VILLA 22); 
/*INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (861, VILLA DEL RO 22); */
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (862,  23); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (863,  23); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (864,  23); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (865, PUERTO 23); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (866, PUERTO CA 23); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (867, PUERTO G 23); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (868, PUERTO LEGU 23); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (869, SAN FRAN 23); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (870, SAN M 23); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (871, SAN 23); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (872, SIB 23); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (873, VALLE DEL GU 23); 
/*INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (874, VILLAG 23); */
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (875, AR 24); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (876, BUENA 24); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (877, CA 24); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (878, CIR 24); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (879, CÓ 24); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (880, FIL 24); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (881, G 24); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (882, LA TE 24); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (883, MONTE 24); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (884,  24); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (885, QUI 24); 
/*INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (886, SA 24); */
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (887, 25); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (888, B 25); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (889, BELÉN DE U 25); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (890, DOS QUEB 25); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (891, GU 25); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (892, LA  25); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (893, LA VIR 25); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (894, MAR 25); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (895, MIS 25); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (896, PE 25); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (897, PUEBLO 25); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (898, QUI 25); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (899,  25); 
/*INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (900,  25); */
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (901, PROVID 26); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (902, SAN A 26); 
/*INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (903, A CAT 26); */
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (904, A 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (905, AL 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (906, AR 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (907, BA 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (908, BARI 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (909, BARRANCABE 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (910, BE 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (911, BO 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (912, BUCARA 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (913, CA 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (914, CALIF 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (915, CAPIT 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (916, CA 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (917, C 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (918, CE 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (919, CH 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (920, C 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (921,  27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (922, CH 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (923, CIMI 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (924, CONCE 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (925, CON 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (926, CONTRAT 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (927, COR 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (928, C 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (929, EL C 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (930, EL GUAC 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (931, EL  27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (932, EL P 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (933, E 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (934, E 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (935, FL 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (936, FLORIDAB 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (937,  27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (938, GA 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (939,  27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (940,  27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (941, GUAD 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (942, GU 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (943, GU 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (944, G 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (945, 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (946, JESÚS  27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (947, J 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (948, LA BE 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (949, L 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (950, LAND 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (951, LE 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (952, LOS S 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (953, MACAR 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (954, M 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (955, MA 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (956, MO 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (957, MOLAG 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (958, OCA 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (959, 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (960, O 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (961, P 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (962, PALMAS DEL SO 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (963, P 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (964, PIEDEC 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (965, PIN 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (966, PUENTE NAC 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (967, PUERTO  27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (968, PUERTO WI 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (969, RIO 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (970, SABANA DE T 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (971, SAN A 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (972, SAN B 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (973, SA 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (974, SAN JO 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (975, SAN JOSÉ DE MI 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (976, SAN M 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (977, CENTE DE CH 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (978, A BÁ 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (979, A H 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (980, SIM 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (981, SO 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (982, S 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (983,  27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (984, S 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (985, 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (986, VALLE SAN 27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (987,  27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (988,  27); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (989, VILLA 27); 
/*INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (990, ZAP 27); */
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (991, BUENA 28); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (992, CA 28); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (993, C 28); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (994, C 28); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (995, CO 28); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (996, EL  28); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (997, GA 28); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (998, GUA 28); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (999, LA  28); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1000, LOS PAL 28); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1001, MAJ 28); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1002, M 28); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1003, O 28); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1004, PA 28); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1005, SA 28); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1006, SAN BENITO 28); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1007, SAN JUAN DE BE 28); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1008, SAN M 28); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1009, SAN O 28); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1010, SAN  28); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1011,  28); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1012, SINC 28); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1013,  28); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1014, 28); 
/*INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1015, TOLU 28);*/ 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1016, ALPU 29); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1017, ALV 29); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1018, AMB 29); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1019, ANZOA 29); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1020, ARMERO (GUAY 29); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1021,  29); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1022, CAJA 29); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1023, CARMEN DE AP 29); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1024, CASAB 29); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1025, CHAP 29); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1026, C 29); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1027, CO 29); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1028, C 29); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1029, DO 29); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1030, ES 29); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1031,  29); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1032, FL 29); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1033, F 29); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1034,  29); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1035, H 29); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1036,  29); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1037, I 29); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1038, ICO 29); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1039, L 29); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1040, L 29); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1041, MARI 29); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1042, M 29); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1043, MU 29); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1044, NATA 29); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1045, O 29); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1046, PALOCA 29); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1047, PIEDRAS PLA 29); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1048,  29); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1049, PURIFIC 29); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1050, RIOB 29); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1051, RONCESV 29); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1052, R 29); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1053, SA 29); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1054, SAN AN 29); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1055, SAN 29); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1056, A I 29); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1057, S 29); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1058, VALLE DE SAN 29); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1059, VENA 29); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1060, VILLAHE 29); 
/*INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1061, VILLA 29); */
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1062, ALCALÁ, 30); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1063, ANDALUCÍA, 30); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1064, ANSERMA NUEVO, 30); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1065, ARGELIA, 30); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1066, BOLÍVAR, 30); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1067, BUENAVENTURA, 30); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1068, BUGA, 30); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1069, BUGALAGRANDE, 30); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1070, CAICEDONIA, 30); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1071, CALI, 30); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1072, CALIMA (DARIEN), 30); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1073, CANDELARIA, 30); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1074, CARTAGO, 30); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1075, DAGUA, 30); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1076, EL AGUILA, 30); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1077, EL CAIRO, 30); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1078, EL CERRITO, 30); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1079, EL DOVIO, 30); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1080, FLORIDA, 30); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1081, GINEBRA GUACARI, 30); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1082, JAMUNDÍ, 30); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1083, LA CUMBRE, 30); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1084, LA UNIÓN, 30); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1085, LA VICTORIA, 30); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1086, OBANDO, 30); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1087, PALMIRA, 30); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1088, PRADERA, 30); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1089, RESTREPO, 30); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1090, RIO FRÍO, 30); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1091, ROLDANILLO, 30); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1092, SAN PEDRO, 30); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1093, SEVILLA, 30); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1094, TORO, 30); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1095, TRUJILLO, 30); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1096, TULÚA, 30); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1097, ULLOA, 30); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1098, VERSALLES, 30); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1099, VIJES, 30); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1100, YOTOCO, 30); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1101, YUMBO, 30); 
/*INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1102, ZARZAL, 30); */
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1103, CARURÚ, 31); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1104, MITÚ, 31); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1105, PACOA, 31); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1106, PAPUNAUA, 31); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1107, TARAIRA, 31); 
/*INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1108, YAVARATÉ, 31);*/ 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1109, CUMARIBO, 32); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1110, LA PRIMAVERA, 32); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1111, PUERTO CARREÑO, 32); 
INSERT INTO rel_dpt_muni (muni_id, depart_id) VALUES (1112, A ROSALIA, 32); 

